version: '3'

services:
    redis:
      image: redis:alpine3.17
      ports:
        - 6379:6379

    flask-api:
      build: ./flask-api
      ports:
        - 5050:5050
      environment:
        FLASK_ENVIRONMENT: dev-compose
      depends_on:
        - redis